version: '3.0'
services:
  web:
    build: ""
    image: 424131214300.dkr.ecr.us-east-1.amazonaws.com/brewant_docker:latest
    ports:
      - "80:3000"
    env_file:
      - .env.staging
volumes:
  mysql: